"""Custom stop words for financial Twitter timelines (twitter notebook).

`add_stop_words(stop_words)` appends domain-specific filler words, ticker
noise and slang (some of it crude, as found in the source text) to an NLTK stop-word
list, so that the frequency ranking surfaces meaningful terms. The list was grown
iteratively from the notebook's paste-ready "candidate stop words" output.
"""
#from twitter
def add_stop_words(stop_words):
    
    stop_words.append('https')
    stop_words.append('http')
    stop_words.append('jimcramer')
    stop_words.append('rt')
    stop_words.append('show')
    stop_words.append('says')
    stop_words.append('stock')
    stop_words.append('like')
    stop_words.append('join')
    stop_words.append('still')
    stop_words.append('also')
    stop_words.append('liked')
    stop_words.append('put')
    stop_words.append('mr')
    stop_words.append('actually')
    stop_words.append('never')
    stop_words.append('name')
    stop_words.append('guys')
    stop_words.append('truly')
    stop_words.append('great')
    stop_words.append('idea')
    stop_words.append('let')
    stop_words.append('mull')
    stop_words.append('tight')
    stop_words.append('staff')
    stop_words.append('easy')
    stop_words.append('trade')
    stop_words.append('ideas')
    stop_words.append('really')
    stop_words.append('want')
    stop_words.append('learn')
    stop_words.append('come')
    stop_words.append('best')
    stop_words.append('hailing')
    stop_words.append('rise')
    stop_words.append('kind')
    stop_words.append('words')
    stop_words.append('always')
    stop_words.append('willing')
    stop_words.append('admit')
    stop_words.append('get')
    stop_words.append('things')
    stop_words.append('wrong')
    stop_words.append('club')
    stop_words.append('driven')
    stop_words.append('appears')
    stop_words.append('taking')
    stop_words.append('trying')
    stop_words.append('rationalize')
    stop_words.append('top')
    stop_words.append('tonight')
    stop_words.append('semis')
    stop_words.append('expect')
    stop_words.append('second')
    stop_words.append('day')
    stop_words.append('mu')
    stop_words.append('roared')
    stop_words.append('week')
    stop_words.append('positive')
    stop_words.append('action')
    stop_words.append('stocks')
    stop_words.append('tonighta')
    stop_words.append('message')
    stop_words.append('think')
    stop_words.append('suit')
    stop_words.append('searing')
    stop_words.append('used')
    stop_words.append('adrenalin')
    stop_words.append('bags')
    stop_words.append('peas')
    stop_words.append('sadly')
    stop_words.append('ca')
    stop_words.append('understanding')
    stop_words.append('spirit')
    stop_words.append('meant')
    
    return stop_words